mongodb:
  uri: "mongodb://admin:password123@mongodb.grade-submission.svc.cluster.local:27017"

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  additionalLabels:
    release: prometheus

image:
  tag: "0.41.0"

extraArgs:
  - --collector.diagnosticdata
  - --collector.replicasetstatus
  - --collector.dbstats
  - --collector.topmetrics
  - --collector.indexstats
  - --collector.collstats
  - --collector.dbstatsfreestorage
  - --collector.currentopmetrics
  - --collector.fcv
  - --log.level=debug