apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: 'YWRtaW4='   ## assumes this is base64 encoded, and interprets as admin
  MONGO_INITDB_ROOT_PASSWORD: 'cGFzc3dvcmQxMjM=' ## assumes this is base64 encoded, and interprets as password123
  CONNECTION_URI: 'bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGIubW9uZ29kYi5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNw=='  ## mongodb://admin:password123@mongodb.mongodb.svc.cluster.local:27017
